# Generated by Django 6.0.3 on 2026-03-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
