# Generated by Django 6.0.3 on 2026-03-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/video/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/img/'),
        ),
    ]
